--------------------------------------------------------
--  File created - Monday-July-15-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "COMMANDES" 
   (	"OID" VARCHAR2(6 BYTE), 
	"PLACDATE" DATE DEFAULT SYSDATE, 
	"PAYTYPE" VARCHAR2(25 BYTE), 
	"SHIPADD" VARCHAR2(7 BYTE), 
	"CID" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "COMMANDES"  IS 'Enregistre des informations sur chaque commande pass�e par un client';
--------------------------------------------------------
--  DDL for Table ADRESSE
--------------------------------------------------------

  CREATE TABLE "ADRESSE" 
   (	"ADDID" VARCHAR2(7 BYTE), 
	"STREET" VARCHAR2(75 BYTE), 
	"CITY" VARCHAR2(35 BYTE) DEFAULT ('MONTREAL'), 
	"STATE" VARCHAR2(2 BYTE) DEFAULT ('QC'), 
	"CODE" VARCHAR2(7 BYTE), 
	"COUNTRY" VARCHAR2(25 BYTE) DEFAULT ('CANADA')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "ADRESSE"  IS 'Enregistre des informations sur l''adresse de chaque chaque potentiel acheteur ayant pass� une commande et chaque fournisseur des jeu vid�os vendus et � vendre';
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "CLIENTS" 
   (	"CID" VARCHAR2(6 BYTE), 
	"FNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CLIADD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "CLIENTS"  IS 'Enregistre des informations sur chaque potentiel acheteur ayant pass� une commande de jeu vid�os';
--------------------------------------------------------
--  DDL for Table DETAILSCOMMANDES
--------------------------------------------------------

  CREATE TABLE "DETAILSCOMMANDES" 
   (	"QUANTITY" NUMBER(10,0) DEFAULT '1', 
	"QCTAXRATE" NUMBER(6,0) DEFAULT ('0.09975'), 
	"CANTAXRATE" NUMBER(6,0) DEFAULT ('0.05'), 
	"SALPRICE" NUMBER(10,0), 
	"OID" VARCHAR2(6 BYTE), 
	"VGID" NUMBER(8,0), 
	"TOTAL" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "DETAILSCOMMANDES"  IS 'Enregistre des informations sur chaque produit dans une commande pass�e par un client';
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "FOURNISSEURS" 
   (	"SID" NUMBER(8,0), 
	"FNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SUPADD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "FOURNISSEURS"  IS 'Enregistre des informations sur chaque fournisseur de jeu vid�os';
--------------------------------------------------------
--  DDL for Table JEUXVIDEOS
--------------------------------------------------------

  CREATE TABLE "JEUXVIDEOS" 
   (	"VGID" NUMBER(8,0), 
	"TITLE" VARCHAR2(70 BYTE), 
	"AUTHORS" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(600 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"PUBLIDATE" DATE, 
	"PURCHPRICE" NUMBER(8,0), 
	"CATALPRICE" NUMBER(10,0), 
	"STOCKNUMBER" NUMBER(6,0), 
	"SID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "JEUXVIDEOS"  IS 'Enregistre des informations sur chaque jeu vid�os vendu et � vendre';
REM INSERTING into COMMANDES
SET DEFINE OFF;
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0010',to_date('20-MAR-20','DD-MON-RR'),'MASTERCARD','TS0001','CL3004');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0011',to_date('20-MAR-20','DD-MON-RR'),'MASTERCARD','RK0002','CL3016');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0012',to_date('21-MAR-20','DD-MON-RR'),'VISA','AG0003','CL3007');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0013',to_date('21-MAR-20','DD-MON-RR'),'PAYPAL','FH0004','CL3011');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0014',to_date('22-MAR-20','DD-MON-RR'),'BANK TRANSFER','KD0005','CL3017');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0015',to_date('01-FEB-20','DD-MON-RR'),'VISA','AB0006','CL3001');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0016',to_date('18-FEB-20','DD-MON-RR'),'MASTERCARD','AS0007','CL3004');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0017',to_date('01-MAR-20','DD-MON-RR'),'PAYPAL','GB0008','CL3009');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0018',to_date('25-FEB-20','DD-MON-RR'),'VISA','AEY009','CL3012');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0019',to_date('15-JAN-20','DD-MON-RR'),'PAYPAL','AD0010','CL3007');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0020',to_date('21-MAR-20','DD-MON-RR'),'MASTERCARD','JJS011','CL3007');
Insert into COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0021',to_date('21-MAR-19','DD-MON-RR'),'VISA','AR0012','CL3017');
REM INSERTING into ADRESSE
SET DEFINE OFF;
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('TS0001','15, Fleury Street','Montreal','QC','H2C 1S7','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('RK0002','19510, 102 Ave','Edmonton','AB','T5S 1K2','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AG0003','50, Hey Ave','Burnaby','QC','V5G 3H7','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('FH0004','437, rue Boyer','Montreal','QC','H2J 3E6','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('KD0005','53, Adanac','Qu�bec','QC','G1C 7B7','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AB0006','240, rue des Nations','Saint-Laurent','QC','H4R 3G4','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AS0007','55, Carey Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('GB0008','35, Ellice Ave','Winnipeg','MB','R3B 1C6','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AEY009','2823, Westmorland St','Fredericton','NB','E3B 3L8','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AD0010','984, Morning Street','Saskatoon ','QC','S7K 3R9','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JJS011','22, Brownlow Ave ','Dartmouth','NS','B3B 1T5','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AR0012','240 Simcoe St N','Oshawa','ON','L1G 0C5','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('CB1013','39112, Empire Ave ','St. John''s','NL','A1E 1W6','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('TS0014','2 Rue des Villes','Qu�bec','SK','S6V 7S4','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('ET0015','1936 Great George St ','Charlottetown','PE','C1A 4K7','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('FH0016','1, Greater Boul','Montreal','QC','H1L 4I4','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JL0017','1130 Idylwyld Dr N','Saskatoon ','SK','S7K 3R5','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JD888','555 Boul St-Laurent #2000','Montreal','QC','H2T 1S6','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JP999','201, 99 Ave','Edmonton','AB','T3X 1K3','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('LA444','33, National Street','Qu�bec','QC','G2A 2D8','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AG222','4003, rue Jean Boyer','Montreal','QC','H1X 3F2','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('PC111','53, Amical Street','Qu�bec','QC','G2D 3F7','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('BJ333','2, Nation Ville','Saint-Laurent','QC','H4R 3G4','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('MS555','555, Danley Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JP777','3995, Space Ave','Winnipeg','MB','R3B 1C6','CANADA');
REM INSERTING into CLIENTS
SET DEFINE OFF;
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3001','Tendulkar','Sachin',null,'tsach@videotron.ca','TS0001');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3002','Rahul','Kapur','587-777-3315','kapurR@yahoo.ca','RK0002');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3003','Ajay','Gandhi','438-456-9870','ag@mail.com','AG0003');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3004','Fifi','Hill','514-789-4561','fifih@hotmail.com','FH0004');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3005','Kapil','Dev','418-251-4587','kapild@gmail.com','KD0005');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3006','Anil','Brousseau','819-564-2150','ab@wanadoo.com','AB0006');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3007','Anabelle','Dessalines','604-683-6159','adessa@gmail.com','AS0007');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3008','Georges','Bosse',null,'georgesb@yahoo.com','GB0008');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3009','Arnold','Marley',null,'amarley@mail.com','AEY009');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3010','Andrew','Dube','905-351-8668','adube@hotmail.com','AD0010');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3011','Jean-Jacques','Saunier','902-835-3727','jjs@mail.com','JJS011');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3012','Anne','Reis',null,'anner@gmail.com','AR0012');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3013','Claude','Bertrand','877-696-3737','claudeb@gmail.com','CB1013');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3014','Tendulkar','Sachin',null,'sachint@mail.com','TS0014');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3015','Emilie','Tremblay','902-367-3447','emiliet@gmail.com','ET0015');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3016','Fifi','Hill',null,'fifih@yahoo.com','FH0016');
Insert into CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3017','Julien','Larouche','866-467-4278','julienL@caramail.com','JL0017');
REM INSERTING into DETAILSCOMMANDES
SET DEFINE OFF;
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (5,0,0,60,'OD0010',9999990,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (4,0,0,60,'OD0010',9999989,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (2,0,0,63,'OD0011',9999988,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,75,'OD0012',9999987,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (5,0,0,103,'OD0013',9999986,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (6,0,0,76,'OD0014',9999990,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (2,0,0,63,'OD0015',9999989,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0016',9999988,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0017',9999987,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (2,0,0,63,'OD0018',9999986,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (3,0,0,63,'OD0010',9999990,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0019',9999989,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0020',9999988,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0021',9999987,null);
Insert into DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values (1,0,0,63,'OD0014',9999986,null);
REM INSERTING into FOURNISSEURS
SET DEFINE OFF;
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (207,'John','Dave','514-999-4500','jod@ubisoft.ca','JD888');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (208,'Josiane','Paul','587-301-3395','josia@nintendo.com','JP999');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (209,'Lucien','Allard','438-555-9520','la@stargam.com','LA444');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (210,'Amelie','Grignard','514-201-4551','amelieg@electro.com','AG222');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (211,'Peppa','Couillard','418-308-4597','pepcouil@sony.com','PC111');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (212,'Benson','Jack','819-999-2990','bjack@sega.com','BJ333');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (213,'Manpreet','Shah','604-666-6666','mshah@nsoft.com','MS555');
Insert into FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values (214,'Jewish','Patel','204-225-0023','jpatel@misoft.com','JP777');
REM INSERTING into JEUXVIDEOS
SET DEFINE OFF;
Insert into JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values (9999990,'Animal Crossing: New Horizons','Nintendo','Animal Crossing: New Horizons is a life simulation video game developed and published by Nintendo. The fifth main series title in the Animal Crossing series, New Horizons was released on the Nintendo Switch on March 20, 2020. ','SIMULATION',to_date('20-MAR-20','DD-MON-RR'),50,60,10,207);
Insert into JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values (9999989,'Murder by Numbers','Mediatonic','Murder by Numbers is a video game developed by Mediatonic and published by The Irregular Corporation. It was released on March 5, 2020 for Nintendo Switch and Microsoft Windows. The game is a hybrid of visual novels with nonogram-style logic puzzles to progress the story. ','PUZZLE',to_date('05-MAR-20','DD-MON-RR'),55,63,8,208);
Insert into JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values (9999988,'Pok�mon Mystery Dungeon: Rescue Team DX','Spike Chunsoft','Pok�mon Mystery Dungeon: Rescue Team DX is a 2020 remake of the 2005 video games Pok�mon Mystery Dungeon: Blue Rescue Team and Red Rescue Team. It is part of the Pok�mon Mystery Dungeon series developed by Spike Chunsoft, published by The Pok�mon Company and distributed by Nintendo for the Nintendo Switch.','ROLE-PLAYING',to_date('06-MAR-20','DD-MON-RR'),60,75,4,209);
Insert into JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values (9999987,'Taur ','Echo Entertainment','Taur is an action-strategy sci-fi game developed and published by Echo Entertainment, released on 20 February 2020.The game is inspired by the tower defense genre and mixes strategy with wave survival.','ACTION',to_date('20-FEB-20','DD-MON-RR'),60,76,8,210);
Insert into JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values (9999986,'FIFA 20','EA Vancouver','FIFA 20 is a football simulation video game published by Electronic Arts as part of the FIFA series. It is the 27th installment in the FIFA series, and was released on 27 September 2019 for Microsoft Windows, PlayStation 4, Xbox One, and Nintendo Switch.','SPORTS',to_date('27-SEP-19','DD-MON-RR'),80,103,12,211);
--------------------------------------------------------
--  DDL for Index OID_COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OID_COMMANDES_PK" ON "COMMANDES" ("OID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDID_ADRESSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDID_ADRESSE_PK" ON "ADRESSE" ("ADDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CID_CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CID_CLIENTS_PK" ON "CLIENTS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SID_FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SID_FOURNISSEURS_PK" ON "FOURNISSEURS" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VGID_JEUXVIDEOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VGID_JEUXVIDEOS_PK" ON "JEUXVIDEOS" ("VGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "COMMANDES" MODIFY ("PLACDATE" CONSTRAINT "PLACDATE_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "COMMANDES" MODIFY ("PAYTYPE" CONSTRAINT "PAYTYPE_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "COMMANDES" MODIFY ("SHIPADD" CONSTRAINT "SHIPADD_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "COMMANDES" ADD CONSTRAINT "PAYTYPE_COMMANDES_CHK" CHECK (PAYTYPE IN('MASTERCARD','VISA','PAYPAL','BANK TRANSFER')) ENABLE;
  ALTER TABLE "COMMANDES" ADD CONSTRAINT "OID_COMMANDES_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADRESSE
--------------------------------------------------------

  ALTER TABLE "ADRESSE" MODIFY ("STREET" CONSTRAINT "STREET_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADRESSE" MODIFY ("CITY" CONSTRAINT "CITY_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADRESSE" MODIFY ("CODE" CONSTRAINT "CODE_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADRESSE" MODIFY ("COUNTRY" CONSTRAINT "COUNTRY_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "ADRESSE" ADD CONSTRAINT "STATE_ADRESSE_CHK" CHECK (STATE IN('AB', 'BC', 'MB', 'NB', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'NL', 'NT', 'YT')) ENABLE;
  ALTER TABLE "ADRESSE" ADD CONSTRAINT "COUNTRY_ADRESSE_CHK" CHECK (COUNTRY IN('CANADA')) ENABLE;
  ALTER TABLE "ADRESSE" ADD CONSTRAINT "ADDID_ADRESSE_PK" PRIMARY KEY ("ADDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "CLIENTS" MODIFY ("FNAME" CONSTRAINT "FNAME_CLIENTS_NN" NOT NULL ENABLE);
  ALTER TABLE "CLIENTS" MODIFY ("LNAME" CONSTRAINT "LNAME_CLIENTS_NN" NOT NULL ENABLE);
  ALTER TABLE "CLIENTS" ADD CONSTRAINT "PHONE_CLIENTS_CHK" CHECK (REGEXP_LIKE (PHONE,'^[2-9]+[0-9]+[0-9]+[-]+[2-9]+[0-9]+[0-9]+[-]+[0-9]{4}')) ENABLE;
  ALTER TABLE "CLIENTS" ADD CONSTRAINT "EMAIL_CLIENTS_CHK" CHECK (REGEXP_LIKE (EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')) ENABLE;
  ALTER TABLE "CLIENTS" ADD CONSTRAINT "CID_CLIENTS_PK" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETAILSCOMMANDES
--------------------------------------------------------

  ALTER TABLE "DETAILSCOMMANDES" MODIFY ("QUANTITY" CONSTRAINT "QUANTITY_DETAILSCOMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "DETAILSCOMMANDES" ADD CONSTRAINT "QUANTITY_DETAILSCOMMANDES_CHK" CHECK (QUANTITY>0) ENABLE;
  ALTER TABLE "DETAILSCOMMANDES" ADD CONSTRAINT "QCTAXRATE_DETAILSCOMMANDES_CHK" CHECK (QCTAXRATE IN(0,009975)) ENABLE;
  ALTER TABLE "DETAILSCOMMANDES" ADD CONSTRAINT "CANTAXRATE_DETAILSCOMMANDES_CHK" CHECK (CANTAXRATE IN(0,005)) ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "FOURNISSEURS" MODIFY ("FNAME" CONSTRAINT "FNAME_FOURNISSEURS_NN" NOT NULL ENABLE);
  ALTER TABLE "FOURNISSEURS" MODIFY ("LNAME" CONSTRAINT "LNAME_FOURNISSEURS_NN" NOT NULL ENABLE);
  ALTER TABLE "FOURNISSEURS" ADD CONSTRAINT "PHONE_FOURNISSEURS_CHK" CHECK (REGEXP_LIKE (PHONE,'^[2-9]+[0-9]+[0-9]+[-]+[2-9]+[0-9]+[0-9]+[-]+[0-9]{4}')) ENABLE;
  ALTER TABLE "FOURNISSEURS" ADD CONSTRAINT "EMAIL_FOURNISSEURS_CHK" CHECK (REGEXP_LIKE (EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')) ENABLE;
  ALTER TABLE "FOURNISSEURS" ADD CONSTRAINT "SID_FOURNISSEURS_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JEUXVIDEOS
--------------------------------------------------------

  ALTER TABLE "JEUXVIDEOS" MODIFY ("TITLE" CONSTRAINT "TITLE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "JEUXVIDEOS" MODIFY ("AUTHORS" CONSTRAINT "AUTHORS_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "JEUXVIDEOS" MODIFY ("CATEGORY" CONSTRAINT "CATEGORY_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "JEUXVIDEOS" MODIFY ("PUBLIDATE" CONSTRAINT "PUBLIDATE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "JEUXVIDEOS" MODIFY ("PURCHPRICE" CONSTRAINT "PURCHPRICE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "CATEGORY_JEUXVIDEOS_CHK" CHECK (CATEGORY IN('ACTION','ACTION-ADVENTURE','ADVENTURE','ROLE-PLAYING','SIMULATION','STRATEGY','SPORTS','PUZZLE','IDLE','OTHER')) ENABLE;
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "PUBLIDATE_JEUXVIDEOS_CHK" CHECK (PUBLIDATE>TO_DATE('2015-12-31','yyyy-mm-dd')) ENABLE;
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "PURCHPRICE_JEUXVIDEOS_CHK" CHECK (PURCHPRICE>0) ENABLE;
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "CATALPRICE_JEUXVIDEOS_CHK" CHECK (CATALPRICE>0) ENABLE;
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "STOCKNUMBER_JEUXVIDEOS_CHK" CHECK (STOCKNUMBER>0) ENABLE;
  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "VGID_JEUXVIDEOS_PK" PRIMARY KEY ("VGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "COMMANDES" ADD CONSTRAINT "SHIPADD_COMMANDES_FK" FOREIGN KEY ("SHIPADD")
	  REFERENCES "ADRESSE" ("ADDID") ENABLE;
  ALTER TABLE "COMMANDES" ADD CONSTRAINT "CID_COMMANDES_FK" FOREIGN KEY ("CID")
	  REFERENCES "CLIENTS" ("CID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "CLIENTS" ADD CONSTRAINT "CLIADD_CLIENTS_FK" FOREIGN KEY ("CLIADD")
	  REFERENCES "ADRESSE" ("ADDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETAILSCOMMANDES
--------------------------------------------------------

  ALTER TABLE "DETAILSCOMMANDES" ADD CONSTRAINT "OID_DETAILSCOMMANDES_FK" FOREIGN KEY ("OID")
	  REFERENCES "COMMANDES" ("OID") ENABLE;
  ALTER TABLE "DETAILSCOMMANDES" ADD CONSTRAINT "VGID_DETAILSCOMMANDES_FK" FOREIGN KEY ("VGID")
	  REFERENCES "JEUXVIDEOS" ("VGID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "FOURNISSEURS" ADD CONSTRAINT "SUPADD_FOURNISSEURS_FK" FOREIGN KEY ("SUPADD")
	  REFERENCES "ADRESSE" ("ADDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEUXVIDEOS
--------------------------------------------------------

  ALTER TABLE "JEUXVIDEOS" ADD CONSTRAINT "SID_JEUXVIDEOS_FK" FOREIGN KEY ("SID")
	  REFERENCES "FOURNISSEURS" ("SID") ENABLE;

--------------------------------------------------------
--  Seqence jeuxvideos
--------------------------------------------------------

CREATE SEQUENCE VGID_JEUXVIDEOS_SEQ
START WITH 1000000
INCREMENT BY -1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

--------------------------------------------------------
--  Seqence FOURNISSEUR
--------------------------------------------------------
CREATE SEQUENCE SID_FOURNISSEURS_SEQ
START WITH 200
INCREMENT BY 1
NOCACHE
NOCYCLE;
